# Generated by Django 4.1 on 2023-01-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0013_auto_20210430_1919"),
    ]

    operations = [
        migrations.CreateModel(
            name="discount",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first", models.IntegerField()),
                ("second", models.IntegerField()),
            ],
        ),
    ]
